### ISSUE TITLE
Return ID of the newly created record

### ISSUE THREAD

**Issue by snow-drop** [jepiqueau/capacitor-sqlite#10]
Good day. I'm currently playing with this plugin and seems good so far. The problem I'm facing right now is I don't know the ID of the newly created record when I run an `INSERT INTO` query. The `run` function only returns  `changes`. The idea came from the `cordova-sqlite` plugin I'm using before in a cordova app and is pretty helpful since I could now query again the newly created record to get the result including the auto-generated ones since I already have the ID.

One workaround is to query the record with the highest primary key or with the latest `dateCreated` or other markers for being latest, but it could have  an overhead than querying by ID.

Also, for some scenario, you could return the ID without querying again the record as you already have the copy of the details of the record except the ID, so you could just attached the returned ID to the copy.

It would be cool if we could have this feature. Thanks! And thank you for developing this awesome plugin! ;)

**Comment by jepiqueau** [comment]
@snow-drop First thanks to use the plugin. Your remark is a positive and i understand your point. It will be taking into account in a future release of the plugin. The "Changes" parameter instead of being an int will be a json object {changes: number, id: any}. Will that fit your need ?. I am currently working hard to add the storage of images through based64 string and validating the code when a field is null. So what is your urgency, can you wait a bit ?

**Comment by jepiqueau** [comment]
@snow-drop on which platform you need it first?

**Comment by snow-drop** [comment]
@jepiqueau Sure no problem ;). I'm grateful that you are helping the ionic capacitor community with this plugin. I don't want to take your time for the functions that you need priority and there are workarounds for my use case so I can wait ;).

As for your question about the platform that I'm going to use it for, I'm currently playing around with Android.

Thank you very much.

**Comment by jepiqueau** [comment]
@snow-drop this is now available in release 2.0.0 of the plugin

**Comment by snow-drop** [comment]
@jepiqueau thank you very much. I'll give it a try. Should I close this issue now or  should I test it first once it's released before closing?

**Comment by jepiqueau** [comment]
@snow-drop Better to test it first and after if successful which should be the case close the issue thanks

**Comment by snow-drop** [comment]
@jepiqueau ok, thanks!

**Comment by snow-drop** [comment]
@jepiqueau Good day. Why the close? I haven't tested your fix yet as I see that in the 'Releases' section in the Github project, It's still on 1.5.3, 25 days ago. Or was it released already? If it is, how could I get the latest release? Thanks!

**Comment by jepiqueau** [comment]
@snow-drop It was released on npm, but i forgot to push it on github, Thanks for your comment, it is done now

**Comment by jepiqueau** [comment]
@snow-drop i re-open it, as i did'nt hear from you i thought it was ok

**Comment by snow-drop** [comment]
@jepiqueau I see. I'm sorry I didn't know that it was already on NPM as I'm just basing on the release section on the github project. I'll check it later and I'll get back here with the results. Thank you!

**Comment by snow-drop** [comment]
I've already tested and it does work with the following output.
```
{
   changes: {
        changes: 1,
        lastId: 4
    }
}
```
 Thank you very much.
