### ISSUE TITLE
SpatiaLite support

### ISSUE THREAD

**Issue by bojanbizjak** [jepiqueau/capacitor-sqlite#11]
Is there any plan or possibility that spatialite will be integrated? 

We are interested in spatialite support on Android, iOS and Electron platform.

**Comment by jepiqueau** [comment]
@bojanbizjak I have not plan for this, i did not even know what is spatialite doing. After a quick search, it seems that it should be a dedicated plugin as i am not sure that one can make it working with SQLCipher. Sorry but i do not think i will go for that trip ...

**Comment by bojanbizjak** [comment]
Thanks for the reply.
