### ISSUE TITLE
Should I open and close the db on each transaction?

### ISSUE THREAD

**Issue by loama** [jepiqueau/capacitor-sqlite#12]
Just a quick performance question.

If I am accessing the db multiple times, should I just keep the db open or there is a good (security or performance) reason to be opening and closing it?

**Comment by jepiqueau** [comment]
@loama Sorry for my late reply, i missed out your question. You do not need to do so. Internally the plugin close the db after each transaction (Insert, Update, Select ...) for security. Hope this is helpful. Can you close the issue.

**Comment by loama** [comment]
Thanks!
