### ISSUE TITLE
error execution in web environment

### ISSUE THREAD

**Issue by jsoret** [jepiqueau/capacitor-sqlite#14]
First thanks for your work JEPIQUEAU, I am following the documentation for trying to run the plugin in the web development environment and then build with capacitor to android but I have this error:

**Error: Uncaught (in promise): Not implemented**

after invoking the open method.

The plugins do not work on the web?

**Comment by jepiqueau** [comment]
@jsoret First thanks for using the plugin. You right, there is no implementation for web. Browsers do not support sqlite storage, this is the reason why you get the message **Not Implemented**.
