### ISSUE TITLE
iOS emulator crashes

### ISSUE THREAD

**Issue by govertbuijs** [jepiqueau/capacitor-sqlite#15]
When i use the plugin on iOS, the emulator crashes with the following error : 
`
Thread 5: Fatal error: Not enough bits to represent the passed value
`

It happens in `UtilsSQLite.swift`, line 100
`sqlite3_bind_int(handle,Int32(idx), Int32(value))`

OS X 10.14.6
XCode 11.3.1

**Comment by erikkemperman** [comment]
I am seeing the same thing!

**Comment by jepiqueau** [comment]
@govertbuijs @erikkemperman First thanks for using the plugin Which value are you passing ?

**Comment by jepiqueau** [comment]
@govertbuijs @erikkemperman Is it when you try storing a boolean value ?

**Comment by jepiqueau** [comment]
@govertbuijs @erikkemperman Can you. give me in few lines what you were trying to do, it will help to test and close the issue Thanks

**Comment by govertbuijs** [comment]
HI @jepiqueau 

I'm storing a milliseconds timestamp (e.g. 1583498806502) into an INTEGER column.
As it doesn't fit in 32 bits, it should have been picked up by the third `if` (`Int64`).
But its type is recognized as an `Int`, which could also be 64 bits (seems to be iOS version dependent).

I'm not a Swift developer, but this seems to work for my case :

```
class func bind( handle: OpaquePointer, value: Any?, idx:Int) throws {
    switch value {
          case .none:
                sqlite3_bind_null(handle, Int32(idx))
          case let value as Double:
                sqlite3_bind_double(handle, Int32(idx), value)
          case let value as String:
                if (value.contains("base64")) {
                    sqlite3_bind_text(handle, Int32(idx), value, -1, SQLITE_TRANSIENT)
                } else if (value.uppercased() == "NULL") {
                    sqlite3_bind_null(handle, Int32(idx))
                } else {
                    sqlite3_bind_text(handle, Int32(idx), value, -1, SQLITE_TRANSIENT)
                }
          case let value as Int32:
                sqlite3_bind_int(handle, Int32(idx), Int32(value))
          case let value as Int64:
                sqlite3_bind_int64(handle, Int32(idx), sqlite3_int64(value))
          case let value as Int:
                sqlite3_bind_int64(handle, Int32(idx), sqlite3_int64(value))
          case let value as Bool:
                var bInt: Int32 = 0
                if (value) {bInt = 1}
                sqlite3_bind_int(handle, Int32(idx), Int32(bInt))
          default:
                throw UtilsSQLiteError.bindFailed
      }
}
```

**Comment by jepiqueau** [comment]
hi @govertbuijs  Thanks for your answer, i think i will use convert any Int in Int64 as for sqlite it is always the type INTEGER. i will do this in the next release. For your example, you should divide by 1000 your timestamp to get it in second this is what i did and it is the reason why i did not see the problem thanks anyhow, you help to make the plugin more reliable

**Comment by jepiqueau** [comment]
@govertbuijs @erikkemperman this should be fixed now on release capacitor-sqlite@2.0.1-3.
Can you test it and close the issue after this

**Comment by govertbuijs** [comment]
Hi @jepiqueau 
This seems fixed, thanks for the quick response and the nice plugin!

**Comment by jepiqueau** [comment]
hi @govertbuijs You are welcome so i close the issue
