### ISSUE TITLE
Electron Databases get deleted with app update

### ISSUE THREAD

**Issue by digaus** [jepiqueau/capacitor-sqlite#16]
Currently the databases are stored under `C:\Users\xxx\AppData\Local\Programs\xxx\Databases`.
This folder however gets cleared when updateing the application.

The DB should be stored under `C:\Users\xxx\AppData\Roaming\xxx\databases` or somewhere similar so it does not get deleted.

**Comment by jepiqueau** [comment]
@digaus Sorry for my late answer i was quite busy on the capacitor-video-player for answering issue. The path you suggest is a good idea but only valid for windows. What do you think about Users\Databases\ApplicationName, I will have a look on the feasibility

**Comment by digaus** [comment]
@jepiqueau 

I am not that familar with electron but maybe we could use `const configDir = (electron.app || electron.remote.app).getPath('userData');` to retrieve a persistent storage location?

**Comment by jepiqueau** [comment]
@digaus This is done release 2.1.0-1
you have to modify the `index.html` file  as follows:

```html
      if (process && typeof (process.versions.electron) === 'string' && process.versions.hasOwnProperty('electron')) {
        const sqlite3 = require('sqlite3');
        const fs = require('fs');
        const path = require('path');
        const homeDir = require('os').homedir();
        window.sqlite3 = sqlite3;
        window.fs = fs;
        window.path = path;
        window.appName = "YOUR_APP_NAME";
        window.homeDir = homeDir;
      }

``` 
New databases location User/Databases/YOUR_APP_NAME/ . Do not forget to copy your old databases in this new location. Hope it will suit your need

**Comment by jepiqueau** [comment]
@digaus Thanks i close the issue
