### ISSUE TITLE
iOS: handling sqlite NULL values

### ISSUE THREAD

**Issue by samirame** [jepiqueau/capacitor-sqlite#18]
Hi!

 while using capacitor-sqlite 2.0.0-3 on iOS, I faced the following exception trying to SELECT some data from a table containing some NULL values. ( the same code works just fine on Android)

```
Fatal error: Unexpectedly found nil while unwrapping an Optional value: 
In file UtilsSQLite.swift
```

It seems that iOS version is not able to handle NULL values. 

Could you please advice?

**Comment by jepiqueau** [comment]
@samirame Hi thanks for using the plugin. Can you give me a bit more about what you were doing. Is the select has been done on a database created with importFromJson or the standard way. If it is the standard way can you give me how the table was created an how the data were inserted so i can have a better understanding.

**Comment by jepiqueau** [comment]
@samirame I have had a field  as TEXT in one of my test databases and i do not insert any data for that field. When i made a Select * i do not have any problem. Did you get on which line the error occurred ? Can you make a simple case  showing the error  and share it on github.

**Comment by samirame** [comment]
Hi! 

Thanks for the follow-up. Here is how I created the table, inserted and selected a row:

```
//table creation
const sqlcmd = `
        BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS mytable (
            tableid INTEGER PRIMARY KEY NOT NULL,
            col1 TEXT NOT NULL,
            col2 TEXT );
...
 COMMIT TRANSACTION;`;
result = await this.sqliteService.execute(sqlcmd);


//insert a row
const col2 = tableData.col2 ? `'${tableData.col2}'` : 'NULL';
let sqlcmd = `INSERT INTO mytable (col1, col2) VALUES ( '${tableData.col1}',${col2})`;
result = await this.sqliteService.run(sqlcmd);


//select a row
const sqlcmd = `SELECT tableid, col1 col2 FROM mytable WHERE col1 = '${term}' COLLATE NOCASE`; 
result = await this.sqliteService.query(sqlcmd);
```

The error occurs in line 165 of function getColumnValue() in UtilsSQLite.swift file:

```
class func getColumnValue(index: Int32, type: Int32, stmt: OpaquePointer) -> Any? {
 switch type {
...
case SQLITE_TEXT:
            let buffer = sqlite3_column_text(stmt, index)
            let val = String(cString:buffer!) // <- line 165:  Fatal error: Unexpectedly found nil while unwrapping an Optional value
            return val
       default:
            return nil
        }
    }
```
Note: I just updated the Sqlite plugin from 2.0.0-3 to the latest (2.1.0-3) and the same code works fine now on iOS. I get back empty string "" for the columns with NULL values.

So it seems that the issue is resolved in the newer version and you can close the issue.

Thank you!

**Comment by jepiqueau** [comment]
@samirame I was testing with 2.1.0-3, reason why i did not get any message, in fact that was modified in 2.1.0-1 to handle null values properly. Usually try to use the latest release of the plugin. Anyhow i am pleased to hear that you do not have any problem now. Do not hesitate to contact me if you are facing new issues. I close the issue
