### ISSUE TITLE
fr: Electron support (sqlite3) and Web support (sql.js)

### ISSUE THREAD

**Issue by digaus** [jepiqueau/capacitor-sqlite#2]
Great work. Looking for an electron solution aswell. For a business application we need to store a lot of data. You mentioned that you forwarded the question to Capacitor team. Any solution yet? 

Wouldnt this solution also work for us:

https://stackoverflow.com/a/57964289

Related issue:
https://github.com/jepiqueau/capacitor-data-storage-sqlite/issues/10

**Comment by digaus** [comment]
I played a bit with your repo but I just cannot wrap my head around his to add electron as a plugin. iOS and Android is ok and will documented but for electron I could not get it to work.

Nevertheless I managed to create a test DB, created a table, insert data and then select the data.

For my project I am already using electron-builder to build the exe. This worked very nicely and I did not have to add any additional plugins expect the sqlite3.

If you could point me in the direction on how to add an electron plugin part I will look into this further.

**Comment by jepiqueau** [comment]
@digaus Thanks for your question, i didn't get any answer from the Ionic Capacitor team. The problem is not to have sqlite running with Electron, the problem is in differentiating the electron plugin from the web plugin which is what i didn't succeed to do. The second problem is that from my first look, i have been rewriting the plugin to get encryption and now use SQLCipher on top of sqlite3. I may have a second look, hoping a better chance of success. The Browsers have no support for SQLite so it is why i use IndexDB for Browsers. Hope this clarify

**Comment by digaus** [comment]
> @digaus Thanks for your question, i didn't get any answer from the Ionic Capacitor team. The problem is not to have sqlite running with Electron, the problem is in differentiating the electron plugin from the web plugin which is what i didn't succeed to do. The second problem is that from my first look, i have been rewriting the plugin to get encryption and now use SQLCipher on top of sqlite3. I may have a second look, hoping a better chance of success. The Browsers have no support for SQLite so it is why i use IndexDB for Browsers. Hope this clarify

Yeah I know this is also where I am currently stuck. Do not know how to integrate electron in the plugin. All I got was "No electron implementation available"

For web there is sql.js which we could try to use.

https://github.com/sql-js/sql.js

Really hope Capacitor team will do something for Electron. Otherwise they should not claim that they support it as a platform.

As a workaround we maybe could just use the web implementation and there check if we are in Electron environment.

**Comment by jepiqueau** [comment]
Yes, this is what i am doing right now on Electron and it works well as IndexDB on browser. I will have a second look later and i will advise you when i will have found the solution

**Comment by digaus** [comment]
> Yes, this is what i am doing right now on Electron and it works well as IndexDB on browser. I will have a second look later and i will advise you when i will have found the solution

I did some tests today: https://github.com/digaus/capacitor-sqlite/pull/1/files

There are some steps needed. User needs to install sqlite3 as dep in electron folder. 

Also needs to include this in script tag of index.html:
   ```
 const sqlite3 = require('sqlite3');
    window.sqlite3 = sqlite3;
```
Then where you want to use it we need to add

`      this._sqlite.sqlite3 = window['sqlite3'];`


Hacky, but it works. Do you have a better solution? If not would you accept a PR with the necessary changes made (README and Sqlite3 implementation)?

**Comment by jepiqueau** [comment]
@digaus i am getting close of releasing the plugin with the Electron support, i thank you for your work.

**Comment by digaus** [comment]
> @digaus i am getting close of releasing the plugin with the Electron support, i thank you for your work.

Thank you for the fast implementation :)

You should add try/catch block arround the script content in the index.html in the README

**Comment by jepiqueau** [comment]
@digaus Thanks for the comments. Yes it is going so fast in Electron that i had to change the code of the app starter which was working find on IOS & Android and step back from Observable to promise as i didn't find what was going on. I will add a try catch block thanks for this. but i am not too much happy with this solution has that give an error message under IOS as process is not known. I was trying to implementing it in Electron but the preload in the window web preference take only one script which is already taken by the capacitor team. i will have an other look later as i want to concentrate on updating the plugin to capacitor 2.0 and to AndroidX as some ask for.

**Comment by seanwu1105** [comment]
@jepiqueau Any updates for web platform support with sql.js?

**Comment by seanwu1105** [comment]
@jepiqueau I understand sql.js only supports a volatile database which might not be a good choice. However, IMHO, supporting web platform would greatly help to debugging or fast prototyping an app as I do not need to build the Capacitor project to emulator or physical devices. I can simply build and serve the app on local browser to verify the functionality just implemented.

sql.js provides a way to export and import the existing sqlite file. Though it is not perfect at all, maybe this project can serialize the sqlite file and store to IndexedDB internally for the persistence.

**Comment by jepiqueau** [comment]
@seanwu1105 Understand your point. I never thought about it.  But in fast prototyping you could use the Electron platform, which works on the "Web browser" allowing you to store the db on your disk. It is as easy as the Web.
you just do the following
```
npx cap sync @capacitor-community/sqlite
npm run build
npx cap copy @capacitor-community/sqlite
npx cap open @capacitor-community/sqlite
```  
instead of
```
npx cap sync
npm run build
npx cap copy web
npx cap serve
``` 
the sql.js project is not even storing the db in indexDB, if it would it could have been much easier. For me is quite a lot of work for not a huge benefit as we can fall back to Electron.
