### ISSUE TITLE
DB don't work after error on insert "PrepareSQL step failed"

### ISSUE THREAD

**Issue by fema16** [jepiqueau/capacitor-sqlite#26]
I have change the cordova plugin to this plugin when I update my app to capacitor, but I have a several problem with this plugin. When I do insert and this query have an error  (e. duplicate primary key, invalid column type, ...) the return is {changes: -1, PrepareSQL step failed}... at this moment all the next querys returns the same error.

To works fine, I have dead the app and open back

**Comment by jepiqueau** [comment]
@fema16 first thanks for using the plugin. i am away from good internet connection till mid next week. It is not clear to me if it is working or if you have still a problem after what you said "dead the app and open back"?

**Comment by jepiqueau** [comment]
@fema16 Is that happened only on IOS plugin

**Comment by jepiqueau** [comment]
@fema16 i did publish a new release 2.2.0-4 where the issue should be fixed. tell me if you still have some problems

**Comment by jepiqueau** [comment]
@fema16 As you did not comeback i close the issue

**Comment by fema16** [comment]
Hi @jepiqueau, 

I'm on holidays and I don't see your answers. Next Monday I will return and test the new realase 2.2.0-4. 

Thanks for all
