### ISSUE TITLE
Import from JSON failing due to PRAGMA

### ISSUE THREAD

**Issue by mpat8121** [jepiqueau/capacitor-sqlite#27]
Hi @jepiqueau,
 
Thanks again for this plugin - we're using it extensively. 

I'm having an issue in iOS only where the ImportFromJson method is failing due to the PRAGMA setup in the createDatabaseSchema method -> https://github.com/jepiqueau/capacitor-sqlite/blob/master/ios/Plugin/DatabaseSQLiteHelper.swift#L528

This fails on the execSQL step in the do block and throws the error "ImportFromJson command failed: Error: execSQL Error: execute failed." 

The contents of the JSON I am attempting to import never get evaluated at all as the method exits before the tables are iterated over.

I've tried using both the "full" and "partial" modes and included/removed the table schemas as required in your documentation. They both produce the same result. 

My app runs two imports to initialise the database tables and some data when the app is opened up which are working fine so it is only when the user is prompted to sync the local database with data from cloud storage that this occurs. 

Is it necessary to run the pragmas on every import and would this call to ImportFromJson conflict with any other queries that may have run or are about to be called?

Let me know what other information might help.

Thanks!

**Comment by jepiqueau** [comment]
@mpat8121 I will have a look but as i took one week of and as  i am away of good internet connection you may have to wait for mid next week. Can you confirm that this happen only with IOS. and works fine for Android and Electron. Are you using foreign keys ? hope you can wait without too much disagreement

**Comment by jepiqueau** [comment]
@mpat8121 i had a quick look but not able to reproduce the problem. i did initially a full import with only the schema of several tables for one database followed by a partial import of some data for some tables followed by another partial import with more table data and it works fine. Can you reproduce the error in a small test app and store it on github so i can have a closer look on a real scenario. Are you using foreign keys in your schema? Sorry for asking you for more work on your side but i think it is necessary to catch this error

**Comment by mpat8121** [comment]
@jepiqueau There is no rush. Enjoy your time off. 
I will try and get a test app up and running replicating the problem. 

To answer your questions:
- I can confirm I'm only seeing this in iOS - the android import seems to be working. I do not have an electron setup to confirm. 
- The tables do contain foreign keys

I _think_ it is related to issue #26 where if one sql command fails, then all subsequent commands fail. 

The sqlite3_exec method in sqlite3.c in the SQLCipher library is returning rc = 5 when the PRAGMA logic is run, which if I'm correct is SQLITE_BUSY (I'm not very familiar with C, nor the SQLite library error codes). 

I think this means that when the sql command fails, neither sqlite3_finalize or sqlite3_close are invoked so the DB is always busy.

I can confirm this as no further query/insert command works after the import referenced above fails.

**Comment by jepiqueau** [comment]
@mpat8121 Can you try just before you do the synchronization to close the db, open it and as first command do your import and tell me if it is still failing? May be the database is not close for unknown reason.

**Comment by jepiqueau** [comment]
@mpat8121 Are you sure that there is no others previous commands still running on other threads at the same time you try to invoke the synchronization. Changing the PRAGMA can only be done when the db is free from any processes

**Comment by mpat8121** [comment]
That was my suspicion as the app does make other calls as part of the page initialisation, however, I haven't been able to prove/prevent this.

I tried forcing the database closed and then open as you suggested but no luck. Still seeing the same issue with return code 5. 

The snippet of the Xcode log showing successful closure and re-opening and then the import in sequence:

To Native ->  CapacitorSQLite close 122776364
⚡️  TO JS {"result":true}
⚡️  [log] - Close result true
⚡️  To Native ->  CapacitorSQLite open 122776365
databaseName: defectsqliteSQLite.db 
path: /var/mobile/Containers/Data/Application/7DA27FCE-DBAF-4CFA-83F3-4DE9380CFFEF/Documents
⚡️  TO JS {"result":true}
⚡️  [log] - Open result true
⚡️  To Native ->  CapacitorSQLite importFromJson 122776366
databaseName: defectsqliteSQLite.db 
path: /var/mobile/Containers/Data/Application/7DA27FCE-DBAF-4CFA-83F3-4DE9380CFFEF/Documents
⚡️  TO JS {"message":"ImportFromJson command failed : Error: execSQL Error: execute failed","changes":{"changes":-1}}
⚡️  [log] - Error importing json categories {"message":"ImportFromJson command failed : Error: execSQL Error: execute failed","changes":{"changes":-1}}

**Comment by jepiqueau** [comment]
@mpat8121 let's continue to have a look

**Comment by mpat8121** [comment]
The rc value is set to 5 when trying the PRAGMA foreign_keys=ON; command. I think the PRAGMA user_version = 1; command is succeding first.

<img width="324" alt="Screen Shot 2020-07-02 at 10 54 11 pm" src="https://user-images.githubusercontent.com/6610593/86361374-14124480-bcb7-11ea-82ca-54d3335eeac2.png">

**Comment by jepiqueau** [comment]
@mpat8121 What was the last SQLIte command on the database before making the synchronization

**Comment by mpat8121** [comment]
A select query that returned zero results:

⚡️  [log] - Running queryCmd SELECT Id, Type, Name, Reference, Created FROM Projects ORDER BY Name COLLATE NOCASE ASC
⚡️  To Native ->  CapacitorSQLite query 29283061
selectSQL: []
⚡️  TO JS {"values":[]}

**Comment by mpat8121** [comment]
@jepiqueau Ok, it's not the importFromJson function and it isn't the PRAGMA's. There were some insert queries occurring earlier than that last select that were failing. Once I bypassed them, the import worked, however, I believe that issue #26 is the root cause.
If an insert query fails, all subsequent database commands fail.
I'll try spin up a demo app for you tomorrow/Saturday to review.
Thanks for your assistance!

**Comment by jepiqueau** [comment]
@mpat8121 i have replace the following function 
```
    // MARK: - ImportFromJson - CreateDatabaseSchema
    
    private func createDatabaseSchema(jsonSQLite:JsonSQLite) throws -> Int {
        var success: Bool = true
        var changes: Int = -1
        guard let db: OpaquePointer = try UtilsSQLite.getWritableDatabase(filename: "\(path)/\(databaseName)",
                    secret:secret) else {
            throw DatabaseHelperError.dbConnection(message:"Error: DB connection")
        }
        if(jsonSQLite.mode == "full") {
            // Set PRAGMAS
            let pragmas: String = "PRAGMA user_version = 1;"
            if sqlite3_exec(db,pragmas, nil, nil, nil) != SQLITE_OK {
                throw DatabaseHelperError.createDatabaseSchema(message: "Error: PRAGMA failed")
            }
        }

        // Start a transaction

        let sql: String = "BEGIN TRANSACTION;"
        if sqlite3_exec(db,sql, nil, nil, nil) != SQLITE_OK {
            throw DatabaseHelperError.createDatabaseSchema(message: "Error: Begin Transaction failed")
        }


        // Create the Database Schema
        var statements: Array<String> = []
        // Loop through Tables
        for i in 0..<jsonSQLite.tables.count {
             if( jsonSQLite.tables[i].schema != nil && jsonSQLite.tables[i].schema!.count > 0) {
                var stmt: String
                if(jsonSQLite.mode == "full") {
                    stmt = "DROP TABLE IF EXISTS "
                    stmt.append(jsonSQLite.tables[i].name)
                    stmt.append(";")
                    statements.append(stmt)
                }

                stmt = "CREATE TABLE IF NOT EXISTS "
                stmt.append(jsonSQLite.tables[i].name)
                stmt.append(" (")
                for j in 0..<jsonSQLite.tables[i].schema!.count {
                    if(jsonSQLite.tables[i].schema![j].column != nil) {
                        stmt.append(jsonSQLite.tables[i].schema![j].column!)
                    } else if(jsonSQLite.tables[i].schema![j].foreignkey != nil) {
                        stmt.append("FOREIGN KEY (\( jsonSQLite.tables[i].schema![j].foreignkey!))")
                    }
                    stmt.append(" ")
                    stmt.append(jsonSQLite.tables[i].schema![j].value)
                    if (j != jsonSQLite.tables[i].schema!.count - 1) {
                        stmt.append(",")
                    }
                }
                stmt.append(");")
                statements.append(stmt);
            }

            if(jsonSQLite.tables[i].indexes != nil && jsonSQLite.tables[i].indexes!.count > 0) {
                for j in 0..<jsonSQLite.tables[i].indexes!.count {
                    var stmt: String
                    stmt = "CREATE INDEX IF NOT EXISTS "
                    stmt.append(jsonSQLite.tables[i].indexes![j].name)
                        
                    stmt.append(" ON ")
                    stmt.append(jsonSQLite.tables[i].name)
                    stmt.append(" (")
                    stmt.append(jsonSQLite.tables[i].indexes![j].column)
                    stmt.append(");")
                    statements.append(stmt);
                }
            }

        }
        if(statements.count > 0) {
            let joined = statements.joined(separator: "\n")
            do {
                changes = try execute(db: db,sql: joined)
                if (changes == -1) {
                    success = false
                } else {
                    let sql: String = "COMMIT TRANSACTION;"
                    print("**** sql create schemas & indexes \(sql)")
                    if sqlite3_exec(db,sql, nil, nil, nil) != SQLITE_OK {
                        throw DatabaseHelperError.createDatabaseSchema(message: "Error: Commit Transaction failed")
                    }
                }
            } catch DatabaseHelperError.execute(let message) {
                throw DatabaseHelperError.importFromJson(message: message)
            }
        } else {
            changes = 0
        }
        if(!success) {
            changes = -1
        }
        if sqlite3_close_v2(db) != SQLITE_OK {
            throw DatabaseHelperError.createDatabaseSchema(message: "Error: createDatabaseSchema closing the database")
        }
        return changes
    }

```
i will try to reproduce now a failed insert to see what is happening

**Comment by jepiqueau** [comment]
@mpat8121 After the import of schemas i did the following insert which are failing
```
      let sqlcmd: string = `
      BEGIN TRANSACTION;
      INSERT INTO settings (id,key,settings) VALUES (1,"Tom","Simpson@example.com");
      INSERT INTO settings (id,key,settings) VALUES (2,"David","Jones@example.com");
      COMMIT TRANSACTION;
      `;         
      result = await this._SQLiteService.execute(sqlcmd);
console.log("insert in settings result.changes.changes ",result.changes.changes)
```
it failed as the column name `settings` is wrong it should be `setting` 
i got  the following messages on Xcode
```
  TO JS {"changes":{"changes":0}}
⚡️  [log] - import result  {"changes":{"changes":0}}
⚡️  To Native ->  CapacitorSQLite execute 6510198
⚡️  TO JS {"changes":{"changes":-1},"message":"Execute command failed : Error: execSQL Error: execute failed"}
⚡️  [log] - insert in settings result.changes.changes  -1
```
and after i did the two imports of data without any problems so i do not see `If an insert query fails, all subsequent database commands fail.` 
So i am waiting your demo do not make it to big so i can download it through 3G phone connection

**Comment by mpat8121** [comment]
@jepiqueau I'm trying to get a demo running that shows this error but am having trouble replicating it.

Can you try simulating the 'prepareSQL' error instead of the execSQL Error? I _think_ the prepareSQL error is where the problem exists.

**Comment by jepiqueau** [comment]
@mpat8121 I did what you ask for, replacing the execute by two run commands followed by a select
```
      if(result.changes.changes === -1 ) resolve(false);
      let sqlcmd: string = "INSERT INTO settings (id,key,settings) VALUES (?,?,?)";
      let values: Array<any>  = [1,"Tom","Simpson@example.com"];
      result = await this._SQLiteService.run(sqlcmd,values);
      console.log("insert 1 in settings result.changes.changes ",result.changes.changes)
      values = [2,"David","Jones@example.com"];
      result = await this._SQLiteService.run(sqlcmd,values);
      console.log("insert 2 in settings result.changes.changes ",result.changes.changes)
      sqlcmd = "SELECT * FROM settings;";
      result = await this._SQLiteService.query(sqlcmd);
      console.log("select result ",result.values.length);
```
and then the two partial imports, everything run fine.
the messages in Xcode are 
```
⚡️  TO JS {"changes":{"changes":0}}
⚡️  [log] - import result  {"changes":{"changes":0}}
⚡️  To Native ->  CapacitorSQLite run 101632705
⚡️  TO JS {"changes":{"changes":-1},"message":"Run command failed : Error: prepareSQL prepare failed"}
⚡️  [log] - insert 1 in settings result.changes.changes  -1
⚡️  To Native ->  CapacitorSQLite run 101632706
⚡️  TO JS {"changes":{"changes":-1},"message":"Run command failed : Error: prepareSQL prepare failed"}
⚡️  [log] - insert 2 in settings result.changes.changes  -1
⚡️  To Native ->  CapacitorSQLite query 101632707
selectSQL: []
⚡️  TO JS {"values":[]}
⚡️  [log] - select result  0
```

**Comment by jepiqueau** [comment]
@mpat8121  Can you try to modify the runSQL and the prepareSQL to see if you still have the error

```
    // MARK: - RunSQL
    
    func runSQL(sql:String,values: Array<Any>) throws -> [String:Int] {
        guard let db: OpaquePointer = try UtilsSQLite.getWritableDatabase(filename: "\(path)/\(databaseName)",
                    secret:secret) else {
            throw DatabaseHelperError.dbConnection(message:"Error: DB connection")
        }
        var message: String = "";
        var lastId: Int = -1
        var changes: Int = 0
        // Start a transaction

        var sqltr: String = "BEGIN TRANSACTION;"
        if sqlite3_exec(db,sqltr, nil, nil, nil) != SQLITE_OK {
            throw DatabaseHelperError.runSql(message: "Error: Begin Transaction failed")
        }
        do {
            changes = try prepareSQL(db: db,sql: sql,values: values)
            if changes > 0 {
                lastId = Int(sqlite3_last_insert_rowid(db))
            }
        } catch DatabaseHelperError.prepareSql(let msg) {
            message = msg
        }
        if lastId != -1 {
            sqltr = "COMMIT TRANSACTION;"
            if sqlite3_exec(db,sqltr, nil, nil, nil) != SQLITE_OK {
                message = "Error: Commit Transaction failed"
            }
        }
        if sqlite3_close_v2(db) != SQLITE_OK {
            message = "Error: runSQL closing the database"
        }
        if(message.count > 0) {
            throw DatabaseHelperError.runSql(message: message)
        } else {
            let result:[String:Int] = ["changes":changes, "lastId":lastId]
            return result
        }
    }

    // MARK: - PrepareSQL
    
    func prepareSQL(db: OpaquePointer,sql: String,values: Array<Any>) throws -> Int {
        var runSQLStatement: OpaquePointer? = nil
        var message: String = "";
        if sqlite3_prepare_v2(db, sql, -1, &runSQLStatement, nil) == SQLITE_OK {
            if !values.isEmpty {
            // do the binding of values
                var idx: Int = 1
                for value in values {
                    do {
                        try UtilsSQLite.bind(handle: runSQLStatement!, value: value, idx: idx)
                        idx = idx + 1
                    } catch {
                        message = "Error: prepareSQL bind failed"
                        break
                    }
                }
            }
            if sqlite3_step(runSQLStatement) != SQLITE_DONE {
                message = "Error: prepareSQL step failed"
            }
        } else {
            message = "Error: prepareSQL prepare failed"
        }
        sqlite3_finalize(runSQLStatement)
        if(message.count > 0) {
            throw DatabaseHelperError.prepareSql(message: message)
        } else {
            let changes: Int = Int(sqlite3_changes(db))
            return changes
        }
    }

```

**Comment by mpat8121** [comment]
@jepiqueau Those changes to the prepare and run seem to have fixed everything. The same sql commands prior to the import are still failing but now the import runs successfully. 
Thanks for your efforts!

**Comment by jepiqueau** [comment]
@mpat8121  i am happy that those changes fix the issue. My intuition was good in fact when  an error was thrown the database was not closed. I will have to revisit the code for all others methods too. All theses fixes will be in the next release which will be published when i am back home sometime mid or end next week. Hope you can work with the temporary fixes sent yesterday till then.  Do you know the reasons why the other sql commands failed prior to the import?

**Comment by mpat8121** [comment]
@jepiqueau Next week is fine. It is probably better that I ensure all SQL commands are working properly rather than relying on the error handling.

Yes, I did find the issue - There were insert commands that were violating the unique constraint on one of the columns in the table being inserted into. 
Interestingly, when I ran the app in Android Studio, the run/debug log produces the full error stack which told me immediately. It is only the iOS version that does not reveal the stack. Perhaps this could be included in a later update?

**Comment by jepiqueau** [comment]
@mpat8121 Can you provide an insert command which was violating the unique constraint so i can look at the ios version why it doesn't reveal the full error stack. Thanks for participating to the debug process it will benefit all the community and make the plugin stronger

**Comment by jepiqueau** [comment]
@mpat8121 Can you try to replace prepareSQL with the following and tell me if it help to grab the previous error
```
    // MARK: - PrepareSQL
    
    func prepareSQL(db: OpaquePointer,sql: String,values: Array<Any>) throws -> Int {
        var runSQLStatement: OpaquePointer? = nil
        var message: String = "";

        var returnCode: Int32 = sqlite3_prepare_v2(db, sql, -1, &runSQLStatement, nil)
        if returnCode == SQLITE_OK {
            if !values.isEmpty {
            // do the binding of values
                var idx: Int = 1
                for value in values {
                    do {
                        try UtilsSQLite.bind(handle: runSQLStatement!, value: value, idx: idx)
                        idx = idx + 1
                    } catch let error as NSError {
                        message = "Error: prepareSQL bind failed " + error.localizedDescription
                        break
                    }
                }
            }
            returnCode = sqlite3_step(runSQLStatement)
            if returnCode != SQLITE_DONE {
                let errmsg: String = String(cString: sqlite3_errmsg(db))
                message = "Error: prepareSQL step failed rc: \(returnCode) message: \(errmsg)"
            }
        } else {
            let errmsg: String = String(cString: sqlite3_errmsg(db))
            message = "Error: prepareSQL prepare failed rc: \(returnCode) message: \(errmsg)"
        }
        returnCode = sqlite3_finalize(runSQLStatement)
        if returnCode != SQLITE_OK {
            let errmsg: String = String(cString: sqlite3_errmsg(db))
            message = "Error: prepareSQL finalize failed rc: \(returnCode) message: \(errmsg)"
        }
        if(message.count > 0) {
            throw DatabaseHelperError.prepareSql(message: message)
        } else {
            let changes: Int = Int(sqlite3_changes(db))
            return changes
        }
    }

```

**Comment by mpat8121** [comment]
@jepiqueau Just in the middle of responding as you provided your last comment.

There is a table defined like this:
`{
      name: "Settings",
      schema: [
        { column: "Id", value: "INTEGER PRIMARY KEY NOT NULL" },
        { column: "Key", value: "TEXT UNIQUE NOT NULL" },
        { column: "Setting", value: "TEXT NOT NULL" },
      ],
}`

and was running the following SQL command twice in the app logic:
"INSERT INTO Settings (Key, Setting) VALUES(?,?)"

If the key already exists then I was getting the error - e.g. ["email", "test@test.com"]

**Comment by mpat8121** [comment]
@jepiqueau Log output from iOS is as follows:

[log] - Running runCmd INSERT INTO Settings (Key,Setting) VALUES (?,?)
⚡️  To Native ->  CapacitorSQLite run 34262567
⚡️  TO JS {"message":"Run command failed : Error: prepareSQL finalize failed rc: 19 message: UNIQUE constraint failed: Settings.Key","changes":{"changes":-1}}

I am unsure of how it will respond to all possible failure types, but this looks to be a good improvement.

**Comment by jepiqueau** [comment]
@mpat8121 Ok, i am implementing this everywhere so it will catch all errors

**Comment by jepiqueau** [comment]
@mpat8121 I did publish the new release 2.2.0-4 tell me if everything looks fine

**Comment by jepiqueau** [comment]
@mpat8121 Did you had time to test the new release, if everything is fine can you please close the issue

**Comment by mpat8121** [comment]
@jepiqueau Yes, I have checked it and everything seems to be running smoothly. This issue is resolved.
