### ISSUE TITLE
where  to  find At the end of the test, two databases should have been created and both are encrypted

### ISSUE THREAD

**Issue by vikashsingh009** [jepiqueau/capacitor-sqlite#3]
I  have  run npx cap open android  and  able  to  run  on  simlator  but  i  cant  able  to  find  sqlite DB  location  ,i  want  to  open  that  sqlite  db  using  sqlite  Db  Browser  how  its  possible?

**Comment by jepiqueau** [comment]
@vikashsingh009 Be sure to have modified the MainActivity.java file as described in the doc and you will see the database under data/data/YOURPACKAGE/databases

**Comment by jepiqueau** [comment]
@vikashsingh009 Did that work for you ?

**Comment by vikashsingh009** [comment]
> @vikashsingh009 Did that work for you ?

Yes @jepiqueau   worked  for  me ,sorry  for  late  response
