### ISSUE TITLE
Invoke capacitor sqlite plugin methods from Custom Plugin 

### ISSUE THREAD

**Issue by jothipandiyanjp** [jepiqueau/capacitor-sqlite#30]
Hi, I am working on implementing custom plugin and in that plugin I want to insert records into sqlite using capacitor sqlite plugin…
Is there any example, where we can call method of one plugin from another plugin…

I have tried, but while calling a method need to pass PluginCall object as parameter… for that i need to pass message handler, PluginCall(this.handler,pluginId,callbackid,methodname,data); what will be the values for this parameters?

Any idea will be helpful for this implementation…

Thanks in advance…

https://forum.ionicframework.com/t/invoke-capacitor-sqlite-plugin-methods-from-custom-plugin/192713

**Comment by jepiqueau** [comment]
@jothipandiyanjp Thanks for looking at the plugin, I have been looking at your question and tried some ideas. I do not think it is feasible as the PluginCall wraps a call from the web layer to native where in fact you would like to access it directly in the native part of your plugin meaning not going through the bridge. So the only way i can think off is to define for the capacitor-sqlite plugin two interfaces one for being call through the bridge and one to be call from native.

**Comment by jothipandiyanjp** [comment]
@jepiqueau Thanks for your reply. Will you add this requirement in your future enhancement?

**Comment by jepiqueau** [comment]
@jothipandiyanjp I am not sure as this requires a complete rewrite of the plugin and on top of this, even if you install the capacitor-sqlite plugin in the custom plugin it seems with my first attempt that you need also to install it in the app using the custom plugin, installing only the custom plugin is not enough.

**Comment by jepiqueau** [comment]
@jothipandiyanjp There is also the question of handling the error messages raised by the capacitor-sqlite in your custom plugin. Are you sure that you cannot develop your app by using the two plugins. The last way would be to take the cdssUtils folder and implements it directly in your custom plugin define mDb = new SQLiteDatabaseHelper(context,dbName+"SQLite.db",encrypted,
                inMode,secret,newsecret,1)
and after this to call directly the SQLiteDatabaseHelper methods
Voilà

**Comment by jothipandiyanjp** [comment]
@jepiqueau  closing this issue. I have added cdssUtils folder in my custom plugin and using it..

**Comment by jepiqueau** [comment]
@jothipandiyanjp Ok, may be in the future i will do two interfaces, so it will be easier for you to update, tell me if you have some issues
