### ISSUE TITLE
Error on responses

### ISSUE THREAD

**Issue by xTancho** [jepiqueau/capacitor-sqlite#6]
Hi, im trying to use this plugins and i have had some problems on android, im going to list them.

1.- When query return no values, it also send a message: "Query command failed", its a lil confusing because its not an error.
![image](https://user-images.githubusercontent.com/58521955/78949668-3a4e8c80-7a9a-11ea-8d44-d953b2dfc370.png)

2.- When there is an error on any kind of query (query, create, insert) its return 1 no -1. ill show my code and pics. (the code is almost the same as the examples)

![image](https://user-images.githubusercontent.com/58521955/78949846-e3958280-7a9a-11ea-8cab-2a1f53b5093c.png)
 i can guess that my error here is because of the index word so it wont create the table.

here is a simple print on execute and run methods
![image](https://user-images.githubusercontent.com/58521955/78950271-36bc0500-7a9c-11ea-9e4d-4a64220737e2.png)

Console:
![image](https://user-images.githubusercontent.com/58521955/78950302-53583d00-7a9c-11ea-88f3-ac9ac2202f67.png)

So the insert will fail too because there is not table with that name.
![image](https://user-images.githubusercontent.com/58521955/78950351-800c5480-7a9c-11ea-9034-03e2d80aeaa5.png)

both responses are set as 1 not -1.

You can test it with ur example angular-sqlite-app-starter and forcing any error.

thx for ur help.

**Comment by xTancho** [comment]
i went a lil deeper and i found this problem
![image](https://user-images.githubusercontent.com/58521955/78951699-062a9a00-7aa1-11ea-9f62-d39f69746b10.png)
when there is an error on catch it wont return -1 because the finally will be always the one who return.

**Comment by jepiqueau** [comment]
@xTancho Thanks for using the plugin, and thanks top point me out this error. I will have a look and make the correction in the next release

**Comment by jepiqueau** [comment]
@xTancho this is now fix in capacitor-sqlite2.0.0-2. thanks again for your cooperation. i close the issue
