### ISSUE TITLE
Not usable in web worker

### ISSUE THREAD

**Issue by piotrblasiak** [jepiqueau/capacitor-sqlite#7]
It seems this package relies on Device.getInfo (which also is not clear, and should not be a requirement?) being called first - but Device.getInfo does not work in web workers.

**Comment by piotrblasiak** [comment]
Nevermind, this actually seems to be a limitation in Capacitor...

**Comment by jepiqueau** [comment]
@piotrblasiak Hi, seems that there is some misunderstanding here. Service-workers are used in web applications as well as PWA which are Web applications. Being Web application they will use the Web part of a capacitor plugin and the not required to use the Device.getInfo as it will return always web. so in PWA app or javascript app you just need to import the plugin. It is only when you develop native applications that you could  access Device.getInfo to identify if the device is an Android or an IOS platform if there are some specifics to a platform required in your application code. Native applications do no use service-workers. To be clear, if you run a PWA app on an Android or IOS platform, it is a browser application not a native application. Hope this clarify. So, as SQLite is not a accessible in Browser mode, the capacitor-sqlite plugin will return not implemented. Hope this clarify
