### ISSUE TITLE
after running  on  Android  studio  generated  file  test-encryptedSQLite  but  open  in sqlitestudio for  table  structure failed

### ISSUE THREAD

**Issue by vikashsingh009** [jepiqueau/capacitor-sqlite#8]
I  have sqlite  db  location  got from simulator ,i  have  changed secret in  GlobelSqlite

public class GlobalSQLite {
    public String secret = "visur@123";
    public String newsecret = "visur@123";
}

after  that  run  on  simulator  to  generate  test-encryptedSQLite.db ,when  i  am opening  on  SQliteStudio with database type SQlCipher  and  load  test-encryptedSQLite.db location  and  passed Cipher  password  which  i  have  given  above its  not  able  to  login  and see  structure.how  to  open  sqlite  file for  viewing strcuture  of  table  in  sqlite 

![Screenshot_9](https://user-images.githubusercontent.com/7962189/79526882-e50b1000-8083-11ea-98d5-eff48c8068ed.png)
![Screenshot_8](https://user-images.githubusercontent.com/7962189/79526885-e6d4d380-8083-11ea-8c18-bbfe00f32c84.png)

**Comment by jepiqueau** [comment]
i think the problem comes from the fact that you make the change in one step you should do it in two steps. you cannot open the database with secret=visur@123 if you do not have run a 
``` 
openStore({database:"test-encryptedSQLite",encrypted:true,mode:"newsecret"})
```
keep the secret as it was before  and change the newsecret by "visur@123" in the GlobalSQLite.java file and run 
``` 
openStore({database:"test-encryptedSQLite",encrypted:true,mode:"newsecret"})
```
change now the secret by "visur@123"  in the GlobalSQLite.java file and now run
```
openStore({database:"test-encryptedSQLite",encrypted:true,mode:"secret"})
```
Now the run should be successful

**Comment by vikashsingh009** [comment]
@jepiqueau ,i  have  tried  above  steps  but  still  not  able  to  open  in  Sqlite  Studio ,i  also  see  logcat  log  like  

2020-04-17 14:12:55.219 32716-324/com.jeep.app.ionic.angular D/SQLiteDatabaseHelper:  **************DataBase File Path /data/user/0/com.jeep.app.ionic.angular/databases/test-sqliteSQLite.db
2020-04-17 14:12:55.219 32716-324/com.jeep.app.ionic.angular D/SQLiteDatabaseHelper:  **************passphrase visur@123

but  even  a  password  is  correct  not  able  to  open  Encripted DB  file

can  you  please  help  me  how to  open  encripted  Sqlite  Db  file to  see  Strcuture  of  table etc

**Comment by jepiqueau** [comment]
@vikashsingh009 It seems that Sqlite studio cannot open an encrypted database, i used DB Browser for SQLite and it works fine.

**Comment by jepiqueau** [comment]
@vikashsingh009 I went a bit further SQLite Studio when you select SQLCipher at Database type and not sqlite3 and you try the Cipher encryption method there is a long list, unfortunately not containing HMAC SHA512 which is the default one in the sqlcipher release i am using.
So the cipher  parameter are:
SQLCipher 4 default
Page Size: 4096
KDF Iterations: 256000
HMAC Algorithm: SHA512
KDF Algorithm: SHA512
May be there is a paid release where you can select the SQLCipher 4 default

So i cannot help you more use DB Browser for SQLite which is free and works

**Comment by vikashsingh009** [comment]
Thanks @jepiqueau ,
But  i have  used  db  browser  for  window  latest  version  where  i  cannot  able  to  open  database  shows  shows  file  is  not  a  database 

![Screenshot_10](https://user-images.githubusercontent.com/7962189/79628452-d04f7a80-815e-11ea-85d9-9b23f474edf5.png)
![Screenshot_11](https://user-images.githubusercontent.com/7962189/79628464-e0675a00-815e-11ea-8b50-472ac8ea276e.png)

**Comment by vikashsingh009** [comment]
@jepiqueau thanks  its  work  now
i  have  to  update   db  browser  for  cipher  latest  nightly  build

**Comment by jepiqueau** [comment]
@vikashsingh009 
my DB Browser about
![image](https://user-images.githubusercontent.com/16580653/79631001-34ba0c00-8156-11ea-8391-9dabc150aa6f.png)

**Comment by vikashsingh009** [comment]
@jepiqueau thanks  for  solving  issues  great  to  work  with  you

**Comment by jepiqueau** [comment]
@vikashsingh009 You are welcome
